version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar

      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true

      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t $DOCKER_TAG .

      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar $DOCKER_TAG

      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar

      - run:
          name: Login to docker
          command: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - push:
          name: Deploy to docker
          command: docker push $DOCKER_TAG

  deploy:
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'b0:2a:e9:7f:0d:67:52:1d:a8:af:7f:b7:fe:c8:f2:dd'
      - deploy:
          name: Deploy to production server
          command: ssh $USER@$SERVER "./deploytucc.sh"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
